server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /quantlectures/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /quantlectures/index.html;
    }

    location = /quantlectures {
        return 301 /quantlectures/;
    }
}
